addSbtPlugin("com.dwijnand"              % "sbt-dynver"                    % "4.1.1")
addSbtPlugin("com.typesafe.sbt"          % "sbt-git"                       % "1.0.0")
addSbtPlugin("de.heikoseeberger"         % "sbt-header"                    % "5.6.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"                  % "0.1.13")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"                  % "2.4.0")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"                 % "1.6.1")
addSbtPlugin("com.timushev.sbt"          % "sbt-updates"                   % "0.5.1")